### ISSUE TITLE
Cancel queries serie

### ISSUE THREAD

**Issue by win32nipuh** [ErikEJ/SqlQueryStress#28]
Run long query *N. Click Cancel - no reaction, cannot cancel the running queries.

**Comment by ErikEJ** [comment]
Unable to repro, please provide detailed repro steps

**Comment by win32nipuh** [comment]
I run 3 long running queries like select * fromlargetable etc. and then click Cancel. 
I wait that it will cancel all running queries in application immediately. But the queries continue to execute.

**Comment by ErikEJ** [comment]
Could you share a screenshot of your settings?

**Comment by Oleg26Dev** [comment]
It seems it was fixed in the fresh version. Please close it.

**Comment by BrentOzar** [comment]
Still present in 0.9.7.49. To repro this, run this query across 10 threads:

WAITFOR DELAY '1:00';

When you click the Cancel button, it doesn't cancel the running WAITFOR queries. The only way to exit the application is to force-kill it, or to kill the queries through SSMS.

**Comment by ErikEJ** [comment]
@BrentOzar I have a pending community PR pending for this! "coming soon"

**Comment by ErikEJ** [comment]
Fixed in latest build!

**Comment by BrentOzar** [comment]
Works great! Thanks sir.

**Comment by Oleg26Dev** [comment]
Yes, it works, thank you
